root: true
env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - airbnb-base
  - airbnb-typescript/base
  - plugin:vue/vue3-recommended
  - '@vue/typescript/recommended'
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
  project: './tsconfig.json'
ignorePatterns:
  - dist
plugins:
  - vue
  - '@typescript-eslint'
rules:
  '@typescript-eslint/semi':
    - error
    - never
  import/first: off
  import/prefer-default-export: off
  no-bitwise:
    - warn
    -
      int32Hint: true
  no-plusplus:
    - error
    -
      allowForLoopAfterthoughts: true
  no-param-reassign:
    - error
    -
      props: false
settings:
  import/resolver:
    typescript: []
