root: true
env:
  browser: true
  es2021: true
parser: 'vue-eslint-parser'
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser' # vue-eslint-parserのオプション
  sourceType: module
  project: './tsconfig.eslint.json'
plugins:
  - vue
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - airbnb-typescript/base
  - plugin:vue/vue3-recommended
  - '@vue/typescript/recommended'
  - prettier
rules:
  '@typescript-eslint/semi':
    - error
    - never
  import/prefer-default-export: off
  no-bitwise:
    - off
    - int32Hint: true
  no-continue:
    - off
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  no-param-reassign:
    - error
    - props: false
settings:
  import/resolver:
    typescript: []
