extends:
  - stylelint-config-recommended-vue
  - stylelint-config-standard
  - stylelint-config-prettier
rules:
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - tailwind
  function-no-unknown:
    - true
    - ignoreFunctions:
        - v-bind
